### ISSUE TITLE
Prompt showing too soon

### ISSUE THREAD

**Issue by davidem** [coolapso/hugo-theme-terminalcv#18]
Hi there, me again. I've found another thing that I can't fix myself. 

The bootsequence works with v2.42.2 and is called 'onInit', but apparently the prompt already shows. It didn't show this behaviour in v2.35.1. See attached recording. 

https://github.com/user-attachments/assets/697d40c5-d160-4630-aa7f-e905f41c61b0

Not sure it is because of your rework. It looks like the bugs [934](https://github.com/jcubic/jquery.terminal/issues/934) and [938](https://github.com/jcubic/jquery.terminal/issues/938) over at jquery.terminal, but they appear to be fixed.

**Comment by coolapso** [comment]
That I think may be because of the way you implemented your boot sequence. it seems to show between "boot sequences"  try putting everything [here](https://github.com/davidem/terminalcv_test/blob/3b84cc45b85577ffab5e661bd693e93f145060a0/themes/terminalcv/layouts/index.html#L423-L453) inside the same timeoutFunctio() instead of having multiple ones

**Comment by davidem** [comment]
I've added everyting in a single loop now (as can be seen [here](https://github.com/davidem/terminalcv_test/blob/293bbe124a145d188ea9cadb3fb5e5c921dcb441/themes/terminalcv/layouts/index.html#L425)), but even then the prompt is showing. Or does your remark still apply here? 😬

**Comment by coolapso** [comment]
not really what I meant but been quite busy lately, not really with the time to tinker with this :/ 

but again, I still believe its not related with the latest changes or with the template itself, but rather how you are implementing the boot sequence. I may be completely wrong as well, so if you find that it was actually something on my end feel free to let me know and i'll fix it. Also If you manage to make the boot sequence more re-usable I'd be happy to integrate it. 

Maybe on the yaml file create an array just for the boot sequence. 

```
params:
  bootsequence:
     boot0: | 
     boot1: |
     boot2: |
     ...
  ```
  
  and loop over the different  the bootsequence  instead of having each section of the boot sequence as a key in the params root.
  didn't give much thought to it, just  throwing some options
