### ISSUE TITLE
Add Posts

### ISSUE THREAD

**Issue by nokijfb** [coolapso/hugo-theme-terminalcv#19]
Hi Coolapso,
I love your work, but I'm not familiar with Hugo (last time I used Jekyll to build a blog). Can we add a post to this "terminal-like" website, so that.. visitors don't need to move to another website to read blog posts?

**Comment by coolapso** [comment]
Hi @nokijfb thanks for reaching out. 

It is still a lot of work for adding blog-like features to the theme, If someone wants to make it and make a pull request I will consider it, but currently it's not something I am interested investing my time in.

**Comment by davidem** [comment]
Hi Carlos, I was also looking into a method for some basic 'blog' functionality. I've created something to suit my needs: 

- blogposts as yaml files in site/data/blog. For some reason I was able to read files in /site/data/blog, not in content. 
  - the yaml files contain 'title', 'author', 'post date' and of course the 'blogpost'
- new command _ls_: to list the files in terminalcv in an 'ls -la' style
- new command _cat <file>_: to show the blogpost content of that specific file. 

The only problem is that I have to run a 'pre-process' script when I export the site with hugo, to add a cat entry in the _switch case_ and a _cat variable_, to show the specific blogpost. So each file in site/data/blog gets a specific entry in index.html. 

I can't seem to find a way around this, as this theme isn't a typical html site. But maybe it is because my lack of programming skills 😉. I can't seem to put input from the terminal into a variable for hugo. What I read on the web is that the site is already built and can't handle ad-hoc variables. 

If this is something you're interested in, please let me know. And I you have an idea how to get rid of the pre-process script, I'm open for suggestions. 

I'll add the specific code later today in a separate branch on my test-repo.

<img width="371" alt="Image" src="https://github.com/user-attachments/assets/a59d28d0-9d14-4ae8-8d79-4cf6571ce822" />
