### ISSUE TITLE
How do I type on mobile?

### ISSUE THREAD

**Issue by kerncos** [coolapso/hugo-theme-terminalcv#2]
On mobile,  the theme cannot call up the system keyboard.

**Comment by coolapso** [comment]
OS & browser Version??

It works for me on android 12 & chrome or brave

I've found out that it is not working on Firefox tho, might be worth looking into it.

**Comment by kerncos** [comment]
Now I'm sure it's because of firefox.

**Comment by pandyah5** [comment]
Hi @4s3ti, first off this is a cool Hugo theme, I wish to use it for my resume! Second I think I know the issue, it stems from jquery.terminal that the theme uses. If we see here, this was an issue flagged on their repo: https://github.com/jcubic/jquery.terminal/issues/846

The fix was pushed in v2.35.1, currently this theme uses v2.33.2 as seen here: https://github.com/4s3ti/terminalcv/blob/ed89dda5ae55ea6fb5c334e70ffad2cd73f01eec/layouts/partials/head.html#L15

If I have your permission, I can edit the version and push a PR.

**Comment by pandyah5** [comment]
Update: I also tested jquery.terminal on my firefox mobile app (Android version 14, Pixel 6) and the keypad appears as expected.

**Comment by coolapso** [comment]
Cool! Go ahead @pandyah5  ;) 

Thank you!

**Comment by pandyah5** [comment]
@4s3ti I have opened a PR to update the jquery.terminal versions. I am still a noob in JS and web dev in general so your review is very much appreciated!
